# frontend/Dockerfile
FROM node:14-slim AS build

WORKDIR /src

COPY package.json ./
RUN npm install

COPY . ./
RUN npm run build

FROM nginx:alpine
COPY --from=build app/dist 

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
