version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend

  backend:
    build:
      context: ./backend
    container_name: backend

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
      - adminer
      - proxy_manager

  proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy_manager
    ports:
      - "8090:81" # Adjusting port to match default NPM port
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  postgres_data:
  data:
