version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports: 
      - "80:5173"

  backend:
    build:
      context: ./backend
    container_name: backend
    ports: 
      - "8000:8000"

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
   environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ewayinka4.
      POSTGRES_DB: hng
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"


  proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy_manager
    ports:
      - "8090:81"
      - "443:443"
      - "81:80"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - postgres
      - backend
      - frontend
      - adminer
      
volumes:
  postgres_data:
  data:
  letsencrypt:
